SET SERVEROUTPUT ON;

DECLARE
u_empno NUMBER;
    u_sal   NUMBER;
BEGIN
    u_empno := TO_NUMBER('&en');

SELECT sal
INTO u_sal
FROM emp
WHERE empno = u_empno;

DBMS_OUTPUT.PUT_LINE('SAL = ' || u_sal);

EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('EMPNO MUST BE A NUMBER');

WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('EMPLOYEE DOES NOT EXIST');

WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('UNEXPECTED ERROR: ' || SQLERRM);
END;
/