-- Create the employee table

CREATE TABLE XX_SAIF_EMPLOYEE
(
    EMPLOYEE_ID      NUMBER PRIMARY KEY,
    EMPLOYEE_NAME    VARCHAR2(100) NOT NULL,
    DEPARTMENT_ID    NUMBER NOT NULL,
    DEPARTMENT_NAME  VARCHAR2(100) NOT NULL,
    JOB_TITLE        VARCHAR2(100),
    SALARY           NUMBER(10,2),
    HIRE_DATE        DATE
);

