-- Employee salary report by department

SELECT
    EMPLOYEE_ID,
    EMPLOYEE_NAME,
    DEPARTMENT_NAME,
    JOB_TITLE,
    SALARY
FROM XX_SAIF_EMPLOYEE
WHERE DEPARTMENT_ID = :P_DEPARTMENT_ID
ORDER BY EMPLOYEE_ID